### ISSUE TITLE
Excution des scripts alembic en échec 

### ISSUE THREAD

**Issue by njouanin** [dataforgoodfr/12_bloom#103]
L'exécution des scripts alembic produit une erreur `ModuleNotFoundError: No module named 'bloom'`.

```
$ alembic upgrade head  
Traceback (most recent call last):
  File "/Users/nicolasjouanin/Dev/python/venv-bloom/bin/alembic", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/nicolasjouanin/Dev/python/venv-bloom/lib/python3.11/site-packages/alembic/config.py", line 641, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/Users/nicolasjouanin/Dev/python/venv-bloom/lib/python3.11/site-packages/alembic/config.py", line 631, in main
    self.run_cmd(cfg, options)
  File "/Users/nicolasjouanin/Dev/python/venv-bloom/lib/python3.11/site-packages/alembic/config.py", line 608, in run_cmd
    fn(
  File "/Users/nicolasjouanin/Dev/python/venv-bloom/lib/python3.11/site-packages/alembic/command.py", line 403, in upgrade
    script.run_env()
  File "/Users/nicolasjouanin/Dev/python/venv-bloom/lib/python3.11/site-packages/alembic/script/base.py", line 583, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/Users/nicolasjouanin/Dev/python/venv-bloom/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicolasjouanin/Dev/python/venv-bloom/lib/python3.11/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/nicolasjouanin/Dev/python/12_bloom/src/alembic/env.py", line 8, in <module>
    from bloom.config import settings
ModuleNotFoundError: No module named 'bloom'
```

**Comment by njouanin** [comment]
Correction:
```
-prepend_sys_path = .
+prepend_sys_path = src/
```
à venir dans la prochaine PR.
