### ISSUE TITLE
Echec du traitement update_vessel_data_voyage.py

### ISSUE THREAD

**Issue by njouanin** [dataforgoodfr/12_bloom#156]
Echec du traitement sur base vide:

```
Traceback (most recent call last):
  File "/home/bloom-dev/12_bloom/src/bloom/infra/database/database_manager.py", line 32, in session
    yield session
  File "/home/bloom-dev/12_bloom/src/bloom/tasks/update_vessel_data_voyage.py", line 65, in run
    vessel_voyage = map_ais_data_to_vessel_voyage(spire_data, vessel)
  File "/home/bloom-dev/12_bloom/src/bloom/tasks/update_vessel_data_voyage.py", line 34, in map_ais_data_to_vessel_voyage
    return VesselVoyage(
  File "/home/bloom-dev/12_bloom/.venv/lib/python3.10/site-packages/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for VesselVoyage
timestamp
  Input should be a valid datetime [type=datetime_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.6/v/datetime_type
Traceback (most recent call last):
  File "/home/bloom-dev/12_bloom/src/bloom/tasks/update_vessel_data_voyage.py", line 86, in <module>
    run()
  File "/home/bloom-dev/12_bloom/src/bloom/tasks/update_vessel_data_voyage.py", line 65, in run
    vessel_voyage = map_ais_data_to_vessel_voyage(spire_data, vessel)
  File "/home/bloom-dev/12_bloom/src/bloom/tasks/update_vessel_data_voyage.py", line 34, in map_ais_data_to_vessel_voyage
    return VesselVoyage(
  File "/home/bloom-dev/12_bloom/.venv/lib/python3.10/site-packages/pydantic/main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for VesselVoyage
timestamp
  Input should be a valid datetime [type=datetime_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.6/v/datetime_type
```

**Comment by njouanin** [comment]
Corrigé par #158
