### ISSUE TITLE
[backend] No such file or directory (os error 2) about ["/project/backend/vessel_width.xlsx"]

### ISSUE THREAD

**Issue by rv2931** [dataforgoodfr/12_bloom#196]
J'ai une erreur qui apparait dans la sortie standard côté backend
Je n'ai pas pris le temps de regarder d'où _a vient mais je le trace ici
Si c'est un fichier à rajouter il faudrait le rajouter au "bundle" du Notion, si c'est un fichier temporaire faudrait voir si il y a un souci ou non
```
bloom_backend   | Traceback (most recent call last):
bloom_backend   |   File "/venv/bin/uvicorn", line 8, in <module>
bloom_backend   |     sys.exit(main())
bloom_backend   |   File "/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
bloom_backend   |     return self.main(*args, **kwargs)
bloom_backend   |   File "/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
bloom_backend   |     rv = self.invoke(ctx)
bloom_backend   |   File "/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
bloom_backend   |     return ctx.invoke(self.callback, **ctx.params)
bloom_backend   |   File "/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
bloom_backend   |     return __callback(*args, **kwargs)
bloom_backend   |   File "/venv/lib/python3.10/site-packages/uvicorn/main.py", line 410, in main
bloom_backend   |     run(
bloom_backend   |   File "/venv/lib/python3.10/site-packages/uvicorn/main.py", line 572, in run
bloom_backend   |     ChangeReload(config, target=server.run, sockets=[sock]).run()
bloom_backend   |   File "/venv/lib/python3.10/site-packages/uvicorn/supervisors/basereload.py", line 52, in run
bloom_backend   |     for changes in self:
bloom_backend   |   File "/venv/lib/python3.10/site-packages/uvicorn/supervisors/basereload.py", line 71, in __next__
bloom_backend   |     return self.should_restart()
bloom_backend   |   File "/venv/lib/python3.10/site-packages/uvicorn/supervisors/watchfilesreload.py", line 84, in should_restart
bloom_backend   |     changes = next(self.watcher)
bloom_backend   |   File "/venv/lib/python3.10/site-packages/watchfiles/main.py", line 121, in watch
bloom_backend   |     raw_changes = watcher.watch(debounce, step, rust_timeout, stop_event)
bloom_backend   | _rust_notify.WatchfilesRustInternalError: error in underlying watcher: IO error for operation on /project/backend/vessel_width.xlsx: No such file or directory (os error 2) about ["/project/backend/vessel_width.xlsx"]
```

**Comment by njouanin** [comment]
je ne vois pas le code bloom à l'origine de l'exception. Tu as plus d'info sur le contexte. En tout cas la lecture d'un fichier nommé `vessel_width.xlsx` ne me dit rien ...

**Comment by njouanin** [comment]
Obsolète
