### ISSUE TITLE
[FRONTEND] Error de compilation (bloquant pour Stack docker)

### ISSUE THREAD

**Issue by rv2931** [dataforgoodfr/12_bloom#341]
Bonjour 
Quand je compile l'image docker du frontend j'ai cette erreur liée au front
On peut adapter la pile docker pour ignorer la compilation du front en attendant mais en l'état ça bloque la compilation et l'utilisation de la Stack docker
Ça vient peut-être d'une chemin ou paramètres a mettre z jour côté docker qui aurait changé côté front ?
```
ERROR [bloom-frontend 4/5] RUN if [ -f yarn.lock ]; then yarn --frozen-lockfile; elif [ -f package-lock.json ]; then npm ci; elif [ -f pnpm-lock.yaml ]; 325.4s ------ > [bloom-frontend 4/5] RUN if [ -f yarn.lock ]; then yarn --frozen-lockfile; elif [ -f package-lock.json ]; then npm ci; elif [ -f pnpm-lock.yaml ];

[...]
Build error occurred 323.4 Error: > Couldn't find any pages or app directory. Please create one under the project root 323.4 at findPagesDir (/app/node_modules/next/dist/lib/find-pages-dir.js:42:15) 323.4 at /app/node_modules/next/dist/build/index.js:235:73 323.4 at async Span.traceAsyncFn (/app/node_modules/next/dist/trace/trace.js:105:20) 323.4 at async build (/app/node_modules/next/dist/build/index.js:185:29) 323.4 at async main (/app/node_modules/next/dist/bin/next:157:5) 323.5 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command. 323.5 error Command failed with exit code 1. ------ failed to solve: process "/bin/sh -c if [ -f yarn.lock ]; then yarn --frozen-lockfile; elif [ -f package-lock.json ]; then npm ci; elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i; else echo \"Warning: Lockfile not found. It is recommended to commit lockfiles to version control.\" && yarn install; fi" did not complete successfully: exit code: 1
```

**Comment by HenriChabert** [comment]
Merci pour la réponse détaillée !
Alors pour ce qui est du build, le problème vient de la séparation de ces deux instructions. NextJS, lorsqu'il est installé, vérifie si un répertoire `pages` ou `app` existe dans le root du projet. NextJS a énormément de règles en termes d'architecture des dossiers et noms des fichiers, donc il vérifie tout ça au moment de l'install.
En faisant un COPY total de tous les dossier avant le `npm install`, tu ne devrais plus avoir le pb. Tu peux également créer un dossier `app` vide dans le dossier de destination avant de copier tout le code.

Pour ce qui est du problème que tu décris, effectivement ça demanderait un peu d'investigation. Pour le moment on fonctionne tous les deux en local sans docker pour le dev.

**Comment by rv2931** [comment]
ce qui est assez bizarre c'est que ça fonctionnait jusqu'à maintenant :) (la réponse IT la plus insupportable qu'il puisse => avant que ça tombe en panne, ça fonctionnait c'est pas normal => ben si en fait mais faut trouver pourquoi) 
je ne crois pas avoir changé quoi que ce soit côté frontend, de votre côté vous avez des idées de ce qui aurait pu changer ?
Dans tous les cas je vais modifier la commande pour faire le COPY total avant npm install
